apiVersion: headscale.infrado.cloud/v1beta1
kind: HeadscalePreAuthKey
metadata:
  name: proxy-nginx-key
  namespace: tenant-test
spec:
  headscaleRef: headscale
  headscaleUserRef: default
  expiration: "720h"
  reusable: false
  ephemeral: true
  secretName: proxy-nginx-preauth-key
