apiVersion: headscale.infrado.cloud/v1beta1
kind: Headscale
metadata:
  name: headscale
  namespace: tenant-test
spec:
  version: "v0.29.2"
  replicas: 1
  persistent_volume_claim:
    size: "256Mi"
    storage_class_name: "nfs-data"
  api_key:
    auto_manage: true
    expiration: "2160h"
    rotation_buffer: "1920h"
  acl_policy:
    inline: |
      {
        "acls": [
          {"action": "accept", "src": ["*"], "dst": ["*:*"]}
        ],
        "autoApprovers": {
          "routes": {
            "10.0.0.0/8": ["*"],
            "192.168.0.0/16": ["*"]
          },
          "exitNode": ["*"]
        }
      }
  config:
    server_url: "https://vpn-test.woowtech.io"
    listen_addr: "0.0.0.0:8080"
    grpc_listen_addr: "0.0.0.0:50443"
    grpc_allow_insecure: true
    metrics_listen_addr: "0.0.0.0:9090"
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
    prefixes:
      v4: "100.64.0.0/10"
      v6: "fd7a:115c:a1e0::/48"
    derp:
      server:
        enabled: false
      urls:
        - "https://controlplane.tailscale.com/derpmap/default"
    dns:
      magic_dns: true
      base_domain: "ts.woowtech.io"
      nameservers:
        global:
          - "1.1.1.1"
          - "8.8.8.8"
    policy:
      mode: database
    log:
      level: info
