apiVersion: headscale.infrado.cloud/v1beta1
kind: HeadscalePreAuthKey
metadata:
  name: test-device-key
  namespace: tenant-test
spec:
  headscaleRef: headscale
  headscaleUserRef: default
  expiration: "72h"
  reusable: true
  ephemeral: false
  secretName: test-device-preauth-key
